#ifndef CODE_HPP
#define CODE_HPP
#include "opcodes.h"

inline void CreateDefaultProgram(BytecodeProgram& program) {
  //Ignore that this is a huge memory leak lol

  /*
  int funcsCount = 1;
  BytecodeInst* main_func = new BytecodeInst[105]{
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 5, 1, -1 },
    { OpCodeI::PRINT_BOOL, PrimitiveType::VOID, 5, -1, -1 },
    { OpCodeI::PRINT_STR_CONST, PrimitiveType::VOID, 0, -1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 5, 0, -1 },
    { OpCodeI::PRINT_BOOL, PrimitiveType::VOID, 5, -1, -1 },
    { OpCodeI::PRINT_STR_CONST, PrimitiveType::VOID, 0, -1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 0, 6, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 8, 2, -1 },
    { OpCodeI::MULT_INT, PrimitiveType::VOID, 0, 8, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 7, 2, -1 },
    { OpCodeI::NEGATE_INT, PrimitiveType::VOID, 7, -1, -1 },
    { OpCodeI::ADD_INT, PrimitiveType::VOID, 0, 7, -1 },
    { OpCodeI::ASSIGN_STR, PrimitiveType::VOID, 10, 1, -1 },
    { OpCodeI::PRINT_STR_VAR, PrimitiveType::VOID, 10, -1, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 7, 0, -1 },
    { OpCodeI::PRINT_NUM, PrimitiveType::INT, 7, -1, -1 },
    { OpCodeI::PRINT_STR_CONST, PrimitiveType::VOID, 0, -1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 1, 6, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 8, 2, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 9, 2, -1 },
    { OpCodeI::MULT_INT, PrimitiveType::VOID, 8, 9, -1 },
    { OpCodeI::NEGATE_INT, PrimitiveType::VOID, 8, -1, -1 },
    { OpCodeI::ADD_INT, PrimitiveType::VOID, 1, 8, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 7, 2, -1 },
    { OpCodeI::NEGATE_INT, PrimitiveType::VOID, 7, -1, -1 },
    { OpCodeI::ADD_INT, PrimitiveType::VOID, 1, 7, -1 },
    { OpCodeI::ASSIGN_STR, PrimitiveType::VOID, 10, 2, -1 },
    { OpCodeI::PRINT_STR_VAR, PrimitiveType::VOID, 10, -1, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 7, 1, -1 },
    { OpCodeI::PRINT_NUM, PrimitiveType::INT, 7, -1, -1 },
    { OpCodeI::PRINT_STR_CONST, PrimitiveType::VOID, 0, -1, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 7, 0, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 8, 2, -1 },
    { OpCodeI::COMPARE_EQ, PrimitiveType::VOID, 7, 8, 2 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 7, 0, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 8, 10, -1 },
    { OpCodeI::COMPARE_EQ, PrimitiveType::VOID, 7, 8, 3 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 5, 2, -1 },
    { OpCodeI::PRINT_BOOL, PrimitiveType::VOID, 5, -1, -1 },
    { OpCodeI::PRINT_STR_CONST, PrimitiveType::VOID, 0, -1, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 5, 3, -1 },
    { OpCodeI::PRINT_BOOL, PrimitiveType::VOID, 5, -1, -1 },
    { OpCodeI::PRINT_STR_CONST, PrimitiveType::VOID, 0, -1, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 5, 2, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 6, 1, -1 },
    { OpCodeI::AND_BOOL, PrimitiveType::VOID, 5, 6, -1 },
    { OpCodeI::JMP_IF, PrimitiveType::VOID, 2, 5, -1 },
    { OpCodeI::ASSIGN_STR, PrimitiveType::VOID, 10, 3, -1 },
    { OpCodeI::PRINT_STR_VAR, PrimitiveType::VOID, 10, -1, -1 },
    { OpCodeI::PRINT_STR_CONST, PrimitiveType::VOID, 0, -1, -1 },
    { OpCodeI::JMP, PrimitiveType::VOID, 1, -1, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 2, -1, -1 },
    { OpCodeI::ASSIGN_STR, PrimitiveType::VOID, 10, 4, -1 },
    { OpCodeI::PRINT_STR_VAR, PrimitiveType::VOID, 10, -1, -1 },
    { OpCodeI::PRINT_STR_CONST, PrimitiveType::VOID, 0, -1, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 1, -1, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 5, 3, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 6, 1, -1 },
    { OpCodeI::AND_BOOL, PrimitiveType::VOID, 5, 6, -1 },
    { OpCodeI::JMP_IF, PrimitiveType::VOID, 4, 5, -1 },
    { OpCodeI::ASSIGN_STR, PrimitiveType::VOID, 10, 5, -1 },
    { OpCodeI::PRINT_STR_VAR, PrimitiveType::VOID, 10, -1, -1 },
    { OpCodeI::PRINT_STR_CONST, PrimitiveType::VOID, 0, -1, -1 },
    { OpCodeI::JMP, PrimitiveType::VOID, 3, -1, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 4, -1, -1 },
    { OpCodeI::ASSIGN_STR, PrimitiveType::VOID, 10, 6, -1 },
    { OpCodeI::PRINT_STR_VAR, PrimitiveType::VOID, 10, -1, -1 },
    { OpCodeI::PRINT_STR_CONST, PrimitiveType::VOID, 0, -1, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 3, -1, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 5, 2, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 6, 3, -1 },
    { OpCodeI::OR_BOOL, PrimitiveType::VOID, 5, 6, -1 },
    { OpCodeI::NOT_BOOL, PrimitiveType::VOID, 5, -1, -1 },
    { OpCodeI::JMP_IF, PrimitiveType::VOID, 5, 5, -1 },
    { OpCodeI::ASSIGN_STR, PrimitiveType::VOID, 10, 7, -1 },
    { OpCodeI::PRINT_STR_VAR, PrimitiveType::VOID, 10, -1, -1 },
    { OpCodeI::PRINT_STR_CONST, PrimitiveType::VOID, 0, -1, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 5, -1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 5, 0, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 6, 0, -1 },
    { OpCodeI::OR_BOOL, PrimitiveType::VOID, 5, 6, -1 },
    { OpCodeI::NOT_BOOL, PrimitiveType::VOID, 5, -1, -1 },
    { OpCodeI::JMP_IF, PrimitiveType::VOID, 6, 5, -1 },
    { OpCodeI::ASSIGN_STR, PrimitiveType::VOID, 10, 8, -1 },
    { OpCodeI::PRINT_STR_VAR, PrimitiveType::VOID, 10, -1, -1 },
    { OpCodeI::PRINT_STR_CONST, PrimitiveType::VOID, 0, -1, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 6, -1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 4, 0, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 7, -1, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 7, 4, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 8, 0, -1 },
    { OpCodeI::COMPARE_LESS, PrimitiveType::VOID, 7, 8, 5 },
    { OpCodeI::NOT_BOOL, PrimitiveType::VOID, 5, -1, -1 },
    { OpCodeI::JMP_IF, PrimitiveType::VOID, 8, 5, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 7, 4, -1 },
    { OpCodeI::PRINT_NUM, PrimitiveType::INT, 7, -1, -1 },
    { OpCodeI::PRINT_STR_CONST, PrimitiveType::VOID, 0, -1, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 7, 4, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 8, 1, -1 },
    { OpCodeI::ADD_INT, PrimitiveType::VOID, 7, 8, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 4, 7, -1 },
    { OpCodeI::JMP, PrimitiveType::VOID, 7, -1, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 8, -1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 7, 0, -1 },
    { OpCodeI::RETURN, PrimitiveType::VOID, 7, -1, -1 },
  };
  BytecodeFunc* funcs = new BytecodeFunc[1]{
    { 105, main_func, 0, "main" },
  };
  int funcTargetsCount = 4;
  String* funcTargets = new String[4]{
    "libc.printf",
    "libc.malloc",
    "libc.free",
    "main",
  };
  int stringsCount = 9;
  String* strings = new String[9]{
    "\n",
    "x=",
    "y=",
    "b1 false",
    "b1 true",
    "b2 false",
    "b2 true",
    "at least one of them is true",
    "false or",
  };

  //*/

  //*
  int funcsCount = 1;
  BytecodeInst* main_func = new BytecodeInst[59]{
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 0, 0, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 1, -1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 1, 1, -1 },
    { OpCodeI::NOT_BOOL, PrimitiveType::VOID, 1, -1, -1 },
    { OpCodeI::JMP_IF, PrimitiveType::VOID, 2, 1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 0, 0, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 3, -1, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 2, 0, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 3, 10, -1 },
    { OpCodeI::COMPARE_LESS, PrimitiveType::VOID, 2, 3, 1 },
    { OpCodeI::NOT_BOOL, PrimitiveType::VOID, 1, -1, -1 },
    { OpCodeI::JMP_IF, PrimitiveType::VOID, 4, 1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 2, 255, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 3, 255, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 4, 255, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 5, 0, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 6, 2, -1 },
    { OpCodeI::FUNC_ARGS, PrimitiveType::VOID, 5, 4, 3 },
    { OpCodeI::FUNC_ARGS, PrimitiveType::VOID, 2, -1, -1 },
    { OpCodeI::CALL_BUILTIN, PrimitiveType::VOID, 6, -1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 7, 500, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 8, 3, -1 },
    { OpCodeI::FUNC_ARGS, PrimitiveType::VOID, 7, -1, -1 },
    { OpCodeI::CALL_BUILTIN, PrimitiveType::VOID, 8, -1, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 9, 0, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 10, 1, -1 },
    { OpCodeI::ADD_INT, PrimitiveType::VOID, 9, 10, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 0, 9, -1 },
    { OpCodeI::JMP, PrimitiveType::VOID, 3, -1, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 4, -1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 0, 0, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 5, -1, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 9, 0, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 10, 10, -1 },
    { OpCodeI::COMPARE_LESS, PrimitiveType::VOID, 9, 10, 1 },
    { OpCodeI::NOT_BOOL, PrimitiveType::VOID, 1, -1, -1 },
    { OpCodeI::JMP_IF, PrimitiveType::VOID, 6, 1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 9, 0, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 10, 0, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 11, 0, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 12, 0, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 13, 2, -1 },
    { OpCodeI::FUNC_ARGS, PrimitiveType::VOID, 12, 11, 10 },
    { OpCodeI::FUNC_ARGS, PrimitiveType::VOID, 9, -1, -1 },
    { OpCodeI::CALL_BUILTIN, PrimitiveType::VOID, 13, -1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 14, 500, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 15, 3, -1 },
    { OpCodeI::FUNC_ARGS, PrimitiveType::VOID, 14, -1, -1 },
    { OpCodeI::CALL_BUILTIN, PrimitiveType::VOID, 15, -1, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 16, 0, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 17, 1, -1 },
    { OpCodeI::ADD_INT, PrimitiveType::VOID, 16, 17, -1 },
    { OpCodeI::MOVE, PrimitiveType::VOID, 0, 16, -1 },
    { OpCodeI::JMP, PrimitiveType::VOID, 5, -1, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 6, -1, -1 },
    { OpCodeI::JMP, PrimitiveType::VOID, 1, -1, -1 },
    { OpCodeI::LABEL, PrimitiveType::VOID, 2, -1, -1 },
    { OpCodeI::ASSIGN_INT, PrimitiveType::VOID, 16, 0, -1 },
    { OpCodeI::RETURN, PrimitiveType::VOID, 16, -1, -1 },
  };
  BytecodeFunc* funcs = new BytecodeFunc[1]{
    { 59, main_func, 0, "main" },
  };
  int funcTargetsCount = 4;
  const char** funcTargets = new const char*[4]{
    "libc.printf",
    "libc.malloc",
    "libc.free",
    "main",
  };
  int stringsCount = 0;
  const char** strings = new const char*[0]{};

  //*/


  program = {
    funcsCount, funcs, funcTargetsCount, funcTargets, stringsCount, strings, false
  };
}

#endif